# Generated by Django 5.0.6 on 2024-08-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('medium', 'Moyenne'), ('high', 'Haute')], default='low', max_length=10),
        ),
    ]
