# Generated by Django 5.0.6 on 2024-08-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='profession',
            field=models.CharField(choices=[('batiments', 'Bâtiments'), ('electricite', 'Electricité'), ('electricite_balisage', 'Electricité balisage'), ('electromecanique', 'Electromécanique'), ('electronique', 'Electronique'), ('electrothermie', 'Electrothermie'), ('exploitation', 'Exploitation'), ('gestion_dechets', 'Gestion des déchets'), ('informatique', 'Informatique'), ('infrastructures', 'Infrastructures'), ('radar_detection', 'Radar Détection'), ('radiocom', 'RadioComm'), ('radionav', 'RadioNav'), ('telecommunications', 'Télécommunications'), ('telecoms', 'Télécoms'), ('ti', 'TI'), ('equipements', 'Tous les équipements'), ('traitement_plan_vol', 'Traitement et plan de vol')], max_length=100),
        ),
    ]
