# Generated by Django 4.1 on 2024-08-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_closedticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedticket',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed')], default='unaffected', max_length=50),
        ),
    ]
