# Generated by Django 4.1 on 2024-08-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_closedticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedticket',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='closedticket',
            name='date_validated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_validated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
