# Generated by Django 4.1 on 2024-08-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_closedticket_date_closed_closedticket_date_validated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedticket',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_ticket', to='myapp.ticket'),
        ),
    ]
