# Generated by Django 4.1 on 2024-08-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_closedticket_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedticket',
            name='ticket',
        ),
    ]
