# Generated by Django 4.1 on 2024-08-11 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_closedticket_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedticket',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_ticket_closures', to='myapp.supervisor'),
        ),
        migrations.AddField(
            model_name='closedticket',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_ticket_validations', to='myapp.technician'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_tickets', to='myapp.supervisor'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_tickets', to='myapp.technician'),
        ),
    ]
