# Generated by Django 4.1 on 2024-08-11 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_closedticket_closed_by_closedticket_validated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedticket',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_closed_tickets', to='myapp.supervisor'),
        ),
        migrations.AlterField(
            model_name='closedticket',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_validated_tickets', to='myapp.technician'),
        ),
    ]
